apiVersion: apps/v1
kind: Deployment
metadata:
  name: bors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bors
  template:
    metadata:
      labels:
        app: bors
    spec:
      imagePullSecrets:
        - name: imagepull
      volumes:
        - name: bors-permissions
          configMap:
            name: bors-permissions
      containers:
        - name: bors
          ports:
            - containerPort: 8080
          env:
            - name: CMD_PREFIX
              value: '@handlebors'
            - name: PERMISSIONS
              value: /etc/bors/permissions
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-cluster-app
                  key: uri
          envFrom:
            - configMapRef:
                # sets the following variables:
                # - APP_ID
                # - OAUTH_CLIENT_ID
                name: github-app
            - configMapRef:
                # - WEB_URL
                name: deployment
            - secretRef:
                # - PRIVATE_KEY
                # - OAUTH_CLIENT_SECRET
                # - WEBHOOK_SECRET
                name: github-app
          volumeMounts:
            - name: bors-permissions
              mountPath: /etc/bors/permissions
